/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp2;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.SQLType;
import java.awt.Component;
/**
 *
 * @author ahmad
 */
public class FormPanel extends javax.swing.JPanel {

    /**
     * Creates new form formPanel
     */
    private Connection con;
    private Form1 parent;
    public FormPanel(Connection con, Form1 parent) {
        initComponents();
        this.con = con;
        this.parent = parent;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        tb_merk = new javax.swing.JTextField();
        tb_plat = new javax.swing.JTextField();
        tb_warna = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(375, 400));
        setMinimumSize(new java.awt.Dimension(375, 400));
        setPreferredSize(new java.awt.Dimension(375, 400));

        jLabel1.setText("Merk");

        jLabel2.setText("Plat");

        jLabel3.setText("Warna");

        jLabel4.setText("Jenis");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Biasa", "Balap", "Sport", "Truk" }));

        jButton1.setText("Submit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_merk, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_plat, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_warna, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tb_merk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tb_plat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tb_warna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jButton1)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        jComboBox1.getAccessibleContext().setAccessibleName("cb_jenis");
        tb_merk.getAccessibleContext().setAccessibleName("tb_merk");
        tb_plat.getAccessibleContext().setAccessibleName("tb_plat");
        tb_warna.getAccessibleContext().setAccessibleName("tb_warna");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String merk = this.tb_merk.getText();
        String plat = this.tb_plat.getText();
        String warna = this.tb_warna.getText();
        String jenis = this.jComboBox1.getSelectedItem().toString();
        if (!merk.isEmpty() && !plat.isEmpty() && !warna.isEmpty() && !jenis.isEmpty()) {
            try {
                PreparedStatement pstmt = this.con.prepareStatement("INSERT INTO mobil (merk,plat,warna,jenis)" + "VALUES(?,?,?,?)", Statement.RETURN_GENERATED_KEYS);
                pstmt.setString(1, merk);
                pstmt.setString(2, plat);
                pstmt.setString(3, warna);
                pstmt.setString(4, jenis);
                int rowaffected = pstmt.executeUpdate();
                if(rowaffected == 1)
                {
                    ResultSet rs = pstmt.getGeneratedKeys();
                    
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
            this.tb_merk.setText("");
            this.tb_plat.setText("");
            this.tb_warna.setText("");
            jComboBox1.setSelectedIndex(0);
            this.parent.bt_form.setVisible(true);
            this.parent.bt_table.setVisible(true);
            this.parent.bt_info.setVisible(true);
        }
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tb_merk;
    private javax.swing.JTextField tb_plat;
    private javax.swing.JTextField tb_warna;
    // End of variables declaration//GEN-END:variables
}
